language: node_js

sudo: required
node_js:
    - 6
before_script:
    - cd source
    - npm install
    - npm audit
    - cd test/mock_target
    - sudo $(which node) app.js &
    - cd ../..
script:
    - node_modules/.bin/gulp lint
    - node_modules/.bin/gulp test
    - node_modules/.bin/cucumber-js test/ --tags @core
